title: Struggle with confusing or poorly documented features.
description: Python, deep-learning and chatbots
author: Pawel Zadrozny
nickname: '@pawelzny'
github: https://github.com/pawelzny
about: I write about confusing or poorly documented features of tools and libraries I use.
disqus_shortname: pawelzny
google_analytics: UA-55876783-5
avatar_url: /static/img/avatar.jpg

timezone: "Europe/Warsaw"

enableTags: true
tagarray: []

#collections:
#  project:
#    output: true
#    permalink: /project/:path/

social:
#    - icon: fa-facebook
#      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/pawelzny"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/pawelzadrozny"
    - icon: fa-stack-exchange
      link: "https://stackexchange.com/users/7527767/pawel"
    - icon: fa-github
      link: "https://github.com/pawelzny"

share:
  twitter_username: pawelzny
  fb_appid:

urls:
    - text: <i class="fas fa-home"></i> Home
      url: "/"
    - text: <i class="fas fa-user-circle"></i> About Me
      url: /about/
    - text: <i class="fas fa-sitemap"></i> Categories
      url: /category/
#    - text: My Projects
#      url: /projects/
    - text: <i class="fas fa-rss-square"></i> XML Feed
      url: /feed.xml

url: "https://pawelzny.com"
baseurl: ""
paginate: 30
per_page: 30
paginate_path: "/page/:num/"
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-gist
  - rouge

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
