# General Jekyll Config
url: http://pawelzny.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
collections:
    npm:
        output: true
gems:
    - jekyll-sitemap
