# General Jekyll Config
url: //pawelzny.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
collections:
  npm:
    output: true
  packagist:
    output: true
gems:
  - jekyll-sitemap
markdown: kramdown
